services:
  kong:
    image: kong/kong:latest
    container_name: kong-oss
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "8000:8000"
      - "8001:8001"
      - "7998:8002"
    volumes:
      - ./kong.yml:/etc/kong/kong.yml:ro
    depends_on:
      - auth-service

  auth-service:
    build: ./auth-service
    container_name: auth-service
    working_dir: /app
    command: sh -lc "php -S 0.0.0.0:9000 -t public"
    volumes:
      - ./auth-service:/app
    depends_on:
      - mysql
    expose:
      - "9000"

  mysql:
    image: mysql:8.4
    container_name: auth-mysql
    environment:
      MYSQL_DATABASE: banking_db
      MYSQL_USER: banking_user
      MYSQL_PASSWORD: banking_pass
      MYSQL_ROOT_PASSWORD: root_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot_pass"]
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  mysql_data: